[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "streamlit run katorikount/src/main.py --server.port $PORT --server.address 0.0.0.0 --server.enableCORS false --server.enableXsrfProtection false --server.headless true"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/"
interval = 30
timeout = 10 